### ISSUE TITLE
websocket行情连接问题

### ISSUE THREAD

**Issue by origingod** [huobiapi/API_Docs#2]
**Websocket的行情用Python版的socketIO_client只有0.5的有效，其他的都有兼容性问题**

**Comment by czheo** [comment]
socket.io protocal升级到1.0以后不兼容以前的版本了，没办法。

**Comment by hualiwang** [comment]
你用的是那个版本？ 我要0.5.6 总会有 socket.error: [Errno 10053] 错误 ，

**Comment by czheo** [comment]
0.5.6应该可以跑。可以参考这个库：https://github.com/czheo/huobi-client-python

**Comment by Angel-fund** [comment]
nodejs 版连接报错： { Error: connect ECONNREFUSED 69.171.224.85:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '69.171.224.85',
  port: 443 }
