### ISSUE TITLE
Python：POST /v1/dw/withdraw/api/create 申请提现虚拟币 (中文和英文文档；请求参数不一样）

### ISSUE THREAD

**Issue by zacchaeusx** [huobiapi/API_Docs#48]
https://api.huobi.pro
POST /v1/dw/withdraw/api/create

哪一个文档是对的呢？俩个不同的请求参数。

我试了全部，都有不同的错误代码。

中文文档error： {'status': 'error', 'err-code': 'gateway-internal-error', 'err-msg': 'Gateway internal error.', 'data': None}

英文文档error: {'status': 'error', 'err-code': 'not-find-security-asset-ga', 'err-msg': 'asset GA cannot be empty', 'data': None}

asset GA 是什么密码？是怎么发送？

如果中文文档的API方式加上：
headers = {'AuthData': '123456'}
在改成英文文档的API参数：‘account-id’ 与 ‘amount’ 后，错误变成：

{'status': 'error', 'err-code': 'ga-need-change', 'err-msg': '尊敬的用户，您的谷歌验证码现已过期，请您更换新的验证码，即可生效', 'data': None}

要怎样发送谷歌验证码呢？

**Comment by all2187** [comment]
What was the solution to this problem?
