### ISSUE TITLE
WWS接口, 返回Ping数据的方式?

### ISSUE THREAD

**Issue by ugksoft** [huobiapi/API_Docs#49]
HTTP 连接,并升级成WWS后 发送明文,以原始流方式发送请求
,可以正常获取到WWS包的行性数据,但是收到两个ping包后,就断开
当收到WWS ping包后:
0. 完全不理会, 到时间,TCP自动被断开,重新即请求可重新获取数据
1.尝试 以WWS的bin或text包发送 ,
2.直接文本 {"pong",xxxx}方式回复  (即和第一次发行性请求时,一样的方式)
3. ,尝试以gz压缩后WWS的bin或原始流方式发送

 都无效,也不报错

 可能会下面情况

1. TCP断掉, 
2.被远程断掉,本地没有收到断掉信号, TCP一直处于假连接状态
3.一直能收到Ping包,无限的收下去, 但是再也收不到行情数据包,请求1min但是好几分种后都没有收到行情分

请问,正确应该以什么数据包方式回应pong包,  发送时,是否要gzlib压缩

**Comment by muyinliu** [comment]
`xxxx` of `{"pong": xxxx}` must be the value of `"ping"` received from WebSocket Server.

For example:
received `{"ping": 18212558000}`
should send `{"pong": 18212558000}`

**Comment by aImondroca** [comment]
我之前也是碰到了同样问题，返回pong无用，后来发现是处理返回数据地方抛异常了，会导致断开连接。异常处理好后基本没有断连情况。所以说有可能是因为其他地方异常，会导致断开。

**Comment by ugksoft** [comment]
客户端,发ping或poing都试过了, 都会数据断流

不过,huobi已经被墙, 已经不会使用了,自己中转数据,又嫌麻烦, 所以,就此结贴
