### ISSUE TITLE
如何拿到api key？

### ISSUE THREAD

**Issue by Iliker** [huobiapi/API_Docs#61]
如何拿到api key？文档的这个地址不对啊
https://www.huobi.com/account/account.php?a=apikeys

**Comment by zixiaomu** [comment]
是这个地址，需登陆火币网账户后查看。

**Comment by Iliker** [comment]
@zixiaomu 奇怪了 换个电脑可以了 多谢了

**Comment by SDIVENSON** [comment]
你好，你那个买入卖出的接口调试好了吗？
